on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3

      - run: npm install -g cordova

      - run: cordova platform add ios
      - run: cordova build ios

      - uses: actions/upload-artifact@v3
        with:
          name: ipa
          path: platforms/ios/build/device

